### ISSUE TITLE
VortoTextString not required without a value throws NullReferenceException

### ISSUE THREAD

**Issue by mortenholmgaard** [mattbrailsford/umbraco-vorto#42] opened 2016-03-03 10:03 UTC
We have a problem when trying to get the value with item.GetVortoValue<string>("header") from an empty VortoTextString field. It happens both with new and existing nodes.

Stacktrace:
```
Header = item.GetVortoValue<string>("header");

[NullReferenceException: Object reference not set to an instance of an object.]
Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoInnerGetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue) +223
Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue, String fallbackCultureName) +115
```

We can see in the umbraco.config cache that only the dtdguid field exists for the property:
```
<header><![CDATA[{
  "dtdguid": "8e902cf2-a6bc-49bb-9e8f-e37e7d102c2d"
}]]></header>
```

When we add text to the fields it works fine.

We are using version 1.5 from nuget and Umbraco 7.4.1.

Is it the intention that one should always use `item.HasVortoValue("header")` first? I think `GetVortoValue()` should return null when there is no value.

**Comment by mattbrailsford** [comment] 2016-03-03 10:16
Sounds like a duplicate of #41,  please try the nightly here https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/1.5.1.36/artifacts

**Comment by mortenholmgaard** [comment] 2016-03-03 10:22
Yes it sounds to be the same problem - I will wait for the nuget update.

**Closed** 2016-03-03 15:20 UTC
