### ISSUE TITLE
Vorto preview with the new doctype editor in Umbraco 7.4

### ISSUE THREAD

**Issue by jbreuer** [mattbrailsford/umbraco-vorto#37] opened 2016-01-31 15:31 UTC
In Umbraco 7.4 the doc type editor previews the datatype. With Vorto it seems to render some Angular code. See attachment. This is an example of a Vorto Textstring.
![vorto74](https://cloud.githubusercontent.com/assets/5444597/12703005/0c06179e-c838-11e5-819e-39601b176583.png)

**Comment by mortenholmgaard** [comment] 2016-03-02 10:54
I have the same problem

**Comment by mattbrailsford** [comment] 2016-03-02 20:05
As there is no official documentation on how property editor developers should handle the preview mode of the new doc type editor, anything we implement would technically be a hack. Given this doesn't break functionality at all, it just doesn't look nice for the developer, my thoughts are to hold of till there is some official guidance on how these should be handled.

**Comment by craigs100** [comment] 2016-03-27 16:29
Don't know if this is a step too far or not related but the content in an RTE in a Grid in Vorto doesn't survive the first language switch. i.e. fr to de ok, back to fr, RTE broken (html showing).

**Comment by mattbrailsford** [comment] 2016-03-27 16:44
Doesn't sound like it, this is purely to do with the preview in the doc
type editor.

Please raise as a separate issue with version numbers and replication
steps.

**Comment by Shazwazza** [comment] 2016-03-27 17:05
My thoughts are that previews (if required) it# should simply be done by css targeting, this might even be possible without any core changes now?

**Comment by mattbrailsford** [comment] 2016-03-27 18:20
I guess the problem is, Vorto has some complex visual ui code, so this is
what is failing as it now needs to render in an environment it's not built
to render in.

In this case, it would probably be best to supply a completely different
view, as it would be a real pain to make it work in both.

I'm not sure what things like the grid do? But I'd imagine there are other
pe's that would struggle too, so it's looking for guidance on what to do in
these scenarios?

**Comment by abjerner** [comment] 2016-03-27 19:08
As a developer of various property editors, a separate view for the preview seems like a good idea to me.

Alternatively we can do some extra checks in the controller of the individual property editors, but right now that would probably be checking if the property editor is within an element with a certain class (that is, hacky at the moment).

Possible there could be an optional config parameter for a preview view, which gives developers some separation between the primary view and the preview view. If not specified, it would be up to the developer to handle the preview in the primary view (or it's controller).

I understand that there might be more important stuff in the pipeline, but some documentation on this would be awesome.

**Comment by Shazwazza** [comment] 2016-03-27 19:24
There is no "documentation" because this isn't something that was really considered. 

A feature request needs to be created (if one doesn't exist already) and we can discuss ways to implement it..... But I don't see what a separate view achieves over just targeting css classes. You can toggle display on/off with this approach which achieves the same thing (and it might actually work as it is today)

**Comment by mattbrailsford** [comment] 2016-03-27 19:40
I agree with anders as like I say, my PE runs logic that doesn't work in
the preview so I either need some way of knowing it's in preview and if so
run some alternative logic or, show some alternative view.

With Vorto, it's ui is built dynamically gathering context from the editor
so there is no way with just pure css to make it look right in the doc type
editor. It'd just be easier to feed it some dummy markup.

I'll go create a core issue.

**Comment by Shazwazza** [comment] 2016-03-27 19:43
Ok cool, well we'll support both ways, I think for many devs it will be just easier to style but if devs need advanced stuff we can register a preview view

**Comment by mattbrailsford** [comment] 2016-03-27 20:02
For sure, my main thing is just to have an official method of doing either, rather than devs just finding ways and means like we usually do :)

I've raised the feature request here http://issues.umbraco.org/issue/U4-8244 so I'll close this issue for now and continue the discussion there as I don't feel any point implemented an interim hack

**Closed by mattbrailsford** 2016-03-27 20:02 UTC
Labels: enhancement

**Comment by AngelRazoJ** [comment] 2016-09-01 17:09
I have the same problem 
what is solution?
