### ISSUE TITLE
Issue converting guid

### ISSUE THREAD

**Issue by JimBobSquarePants** [mattbrailsford/umbraco-vorto#31] opened 2015-11-28 03:03 UTC
Hey chum,

We're getting error logs shown in our install. Which is **Vorto for Umbraco 1.4.0** on **Umbraco 7.3.1**

``` xml
Our.Umbraco.Vorto.Converters.VortoValueConverter - Error converting Vorto value
Newtonsoft.Json.JsonSerializationException: Error converting value 0 to type 'System.Guid'. Path 'dtdguid', line 5, position 15. ---> System.ArgumentException: Could not cast or convert from System.Int64 to System.Guid.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

This is getting thrown here:
https://github.com/mattbrailsford/Vorto/blob/938c9e6a8c1c1f74819726eef9a6948a3ec85b06/Src/Our.Umbraco.Vorto/Converters/VortoValueConverter.cs#L32

Now I have noticed that the default value in your JavaScript is not a valid guid but I don't know what would cause that property to not be populated. Any idea?
https://github.com/mattbrailsford/Vorto/blob/938c9e6a8c1c1f74819726eef9a6948a3ec85b06/Src/Our.Umbraco.Vorto/Web/UI/App_Plugins/Vorto/js/vorto.js#L31

**Comment by mattbrailsford** [comment] 2015-11-28 09:42
Hey Bud,

Are you using this in conjunction with anything else? Like DTGE? Or NC?

If so, I think I might know the issue. Strangly I have this issue raised 3
times this week :)

Gonna try and take a look this w/e to see if I can find a way around it.

**Comment by JimBobSquarePants** [comment] 2015-11-28 13:40
We are using nested content but not in the document types in question. I'm assuming DTGE is the grid editor? If so, no I still haven't played with that yet.

One of my colleagues was able to re-save the doctype and the properties reassigned the guid so I'm not sure what is going on.

**Comment by mattbrailsford** [comment] 2015-11-28 18:14
Hmm, weird. I'm not sure what's going on there then as I can't replicate it.

Gonna close this issue for now, but if it comes back and you can provide any additional info to help narrow it down, I'll happily reopen it.

**Comment by JimBobSquarePants** [comment] 2015-11-29 00:23
No worries, I think you should probably use an empty Guid as your default scope value though so your converter doesn't error.

**Comment by mattbrailsford** [comment] 2015-11-29 08:15
Will do, thanks bud

**Comment by kgiszewski** [comment] 2015-12-16 15:00
Getting this a lot lately. What fixes it for me is to save the content node in the UI that holds the property editor. The issue with this is if you refresh you DB from somewhere else, you may have to save each individual node as it will return `null` if something goes wrong. 

Would returning any empty string be acceptable if I sent you a PR?

It would return blank, but avoid a YSOD downstream and avoid having to null check every `GetVortoValue<>`

It's this line: https://github.com/mattbrailsford/umbraco-vorto/blob/938c9e6a8c1c1f74819726eef9a6948a3ec85b06/Src/Our.Umbraco.Vorto/Converters/VortoValueConverter.cs#L35

**Comment by kgiszewski** [comment] 2015-12-16 15:03
Sent you a PR if interested: https://github.com/mattbrailsford/umbraco-vorto/pull/34

**Comment by kgiszewski** [comment] 2015-12-16 23:08
The issue remains for me. We have a few dozen nodes with a couple of Vorto values on each. When I get a new DB update from a colleague, Vorto throws the error above and returns null until I save each and every node individually. The page that throws the errors is a listing of all of the nodes. 

The DB update is simply a dump of the current setup from someone else's computer. We have to do this due to the geographic distance between myself and the production/dev server. My PR was intended to at least return a default value so that the page wouldn't die. It works fine (though the values are blank) and I can see which item to publish manually in the backoffice.

I realize the root issue is deeper than just returning a default value when an error is thrown. Just throwing my observations into the mix here. I might look at the JSON of a node that throws this error tomorrow to see if the GUID is really an integer.

**Comment by JimBobSquarePants** [comment] 2015-12-21 03:10
Hey chum, 

I'm gonna have to request that this gets reopened. It's happening far too often to ignore and there's some pressure from above now to figure it out. Unfortunately I'm clueless as to how any of this works so I can't replicate it to debug.

**Comment by mattbrailsford** [comment] 2015-12-21 07:54
No worries,

Are you using anything that might affect this? such as courier or usync? Or are you doing anything similar to what @kgiszewski reported? (moving databases). I wonder if you are able to get a DB dump of a property value that is erroring? (ie, before re-saving and fixing it). I'm not quite sure what would cause the guid value to be empty, so just trying to see if something could be interfering.

Cheers

Matt

**Comment by mattbrailsford** [comment] 2015-12-21 07:58
Also, do you have vorto nested inside anything like nested content? or the likes?

Cheers

Matt

**Comment by JimBobSquarePants** [comment] 2015-12-21 08:40
Thanks... Really appreciate it!

There's no nesting of Vorto content and it seems to happen sporadically. No db changes and the site had been ticking along. Seemed to just happen with a content change.

I'll scour through the logs tomorrow morning to see if I can pull any additional detail.

**Comment by mattbrailsford** [comment] 2015-12-21 09:12
Looking at the code, the only thing I could think is happening is if the pe
is being saved before it has chance to load it's init services. The last
service to run sets the guid, so if it doesn't run, it doesn't get set.

One improvement I could make is that I seem to be reseting the value
evertime, rather keeping any saved value, in just updating it. This could
explain the sporadic nature, ie, maybe there is a small lag and it gets
saved before its ready, so it gets set back to zero.

I'll make an update and push it to the repo so you can test the nightly
build.

Matt

**Comment by mattbrailsford** [comment] 2015-12-21 10:03
I've pushed the fix I just mentioned to the git repo, but appveyor seems to be having issues building atm.

If you just want to apply the fix yourself though, it's just a case of updating the JS line you highlighted @JimBobSquarePants to the following

    $scope.model.value = $scope.model.value || {
        values: {},
        dtdguid: "00000000-0000-0000-0000-000000000000"
    };

This basically says re-use $scope.model.value along with the saved dtdguid untill you get told otherwise to update, rather than what was there before, where the dtdguid ALWAYS got set back to an empty guid and then got re-fetched.

Let me know if this helps

Matt

**Comment by JimBobSquarePants** [comment] 2015-12-21 10:42
Thanks for that, I'll give it a go in the morning and feedback.

**Comment by mattbrailsford** [comment] 2016-01-25 08:08
@JimBobSquarePants have you seen this issue since the fix was applied? or can I consider this issue closed?

**Comment by JimBobSquarePants** [comment] 2016-01-26 02:23
Sorry, I meant to get back to you. No, no issues once the fix had been applied. Thanks!

**Comment by mattbrailsford** [comment] 2016-01-26 07:43
Awesome! Thanks @JimBobSquarePants

**Closed by mattbrailsford** 2016-01-26 07:43 UTC
Labels: bug

**Comment by JimBobSquarePants** [comment] 2016-01-26 09:20
No worries :smile: thanks for fixing it! :+1:

**Comment by jbreuer** [comment] 2016-08-02 07:48
I've upgraded to Vorto 1.5.2, but I still see this error in the logs. Is that because I did not resave all the nodes yet?

**Comment by mattbrailsford** [comment] 2016-08-02 08:04
@jbreuer quite likely as you'll need to resave the values so that they get a valid guid, otherwise they are still using the empty guid value.
